# Generated by Django 2.1.1 on 2019-11-14 20:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='lp3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkuid', models.BigIntegerField()),
                ('area', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32737)),
            ],
        ),
    ]
