# Generated by Django 2.1.1 on 2019-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_lp3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lp3',
            options={'verbose_name_plural': 'lp3'},
        ),
    ]
